# Verion of docker-compose to use 
version: "3.17"

services:
  drf:
    build:
      context: . #Sets the directory for docker-compose to build.

    # Maps port on the local machine to port on Docker image
    ports:
      - "8000:8000"

    volumes:
      # Copy changes made to the project to your image in real-time.
      - .:/drf
      # Handles the command used to run the project in the Docker container.
    command: sh -c "python3.10 manage.py runserver 0.0.0.0:8000"

    environment:
      - DB_HOST=db
      - DB_NAME=indicatorsdb
      - DB_USER=admin
      - DB_PASS=1!2@3#4$YanMiller
    depends_on:
      db:


  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=indicatorsdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1!2@3#4$YanMiller
    healthcheck:
      test: ... # Command to check health.
      interval: 5s # Interval between health checks.
      timeout: 5s # Timeout for each health checking.
      retries: 20 # Hou many times retries.
      start_period: 10s # Estimated time to boot.
    restart: unless-stopped
